<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <Target Name="RemoveUnnecessaryWebView2References" AfterTargets="ResolvePackageDependenciesForBuild">
        <ItemGroup>
            <Reference Remove="$(NugetRoot)\lib_manual\netcoreapp3.0\Microsoft.Web.WebView2.WinForms.dll" Condition="'$(UseWindowsForms)' != 'true'" />
            <Reference Remove="$(NugetRoot)\lib_manual\net5.0-windows10.0.17763.0\Microsoft.Web.WebView2.Wpf.dll" Condition="'$(UseWpf)' != 'true'" />
        </ItemGroup>
        <Message Importance="High" Text="Removed WebView2 WPF / WinForms DLL reference." />
    </Target>
  
</Project>
